### ISSUE TITLE
Type in documentation `treshold_rules` > `threshold_rules`

### ISSUE THREAD

**Issue by ShimonOhayon** [mineiros-io/terraform-google-billing-budget#16]
2 small typos in the `README.md` file
[here](https://github.com/mineiros-io/terraform-google-billing-budget/blob/main/README.md?plain=1#L70) and [here](https://github.com/mineiros-io/terraform-google-billing-budget/blob/main/README.md?plain=1#L152) .

I figure it's better to report those since it's making the example section to fail as it is now

**Comment by soerenmartius** [comment]
Hi!

Thanks for pointing this out! We're using a structured format using [terradoc](https://github.com/mineiros-io/terradoc) for providing READMEs. I've updated the source file and re-generated the README in https://github.com/mineiros-io/terraform-google-billing-budget/pull/18.

Again, thanks for bringing this to our attention!
